/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCESNLPsolver_model_ ## ID
#endif

#include <math.h> 
#include "FORCESNLPsolver_model.h"

#ifndef casadi_real
#define casadi_real FORCESNLPsolver_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[14] = {1, 7, 0, 1, 2, 3, 4, 4, 4, 4, 0, 0, 0, 0};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s5[31] = {5, 7, 0, 4, 8, 9, 10, 14, 17, 21, 0, 1, 2, 3, 0, 1, 3, 4, 0, 1, 0, 1, 2, 3, 0, 1, 3, 0, 1, 3, 4};

/* FORCESNLPsolver_objective_0:(i0[7],i1[2])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=100.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a1=casadi_sq(a1);
  a1=(a0*a1);
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[1]? arg[1][1] : 0;
  a2=(a2-a3);
  a2=casadi_sq(a2);
  a0=(a0*a2);
  a1=(a1+a0);
  a0=1.0000000000000001e-01;
  a2=arg[0]? arg[0][0] : 0;
  a2=casadi_sq(a2);
  a2=(a0*a2);
  a1=(a1+a2);
  a2=arg[0]? arg[0][1] : 0;
  a2=casadi_sq(a2);
  a0=(a0*a2);
  a1=(a1+a0);
  if (res[0]!=0) res[0][0]=a1;
  return 0;
}

int FORCESNLPsolver_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int FORCESNLPsolver_objective_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver_objective_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver_objective_0_free_mem(int mem) {
}

int FORCESNLPsolver_objective_0_checkout(void) {
  return 0;
}

void FORCESNLPsolver_objective_0_release(int mem) {
}

void FORCESNLPsolver_objective_0_incref(void) {
}

void FORCESNLPsolver_objective_0_decref(void) {
}

casadi_int FORCESNLPsolver_objective_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolver_objective_0_n_out(void) { return 1;}

casadi_real FORCESNLPsolver_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int FORCESNLPsolver_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver_dobjective_0:(i0[7],i1[2])->(o0[1x7,4nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=1.0000000000000001e-01;
  a1=arg[0]? arg[0][0] : 0;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0]? arg[0][1] : 0;
  a1=(a1+a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=100.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[0]? arg[0][3] : 0;
  a2=arg[1]? arg[1][1] : 0;
  a1=(a1-a2);
  a1=(a1+a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][3]=a0;
  return 0;
}

int FORCESNLPsolver_dobjective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int FORCESNLPsolver_dobjective_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver_dobjective_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver_dobjective_0_free_mem(int mem) {
}

int FORCESNLPsolver_dobjective_0_checkout(void) {
  return 0;
}

void FORCESNLPsolver_dobjective_0_release(int mem) {
}

void FORCESNLPsolver_dobjective_0_incref(void) {
}

void FORCESNLPsolver_dobjective_0_decref(void) {
}

casadi_int FORCESNLPsolver_dobjective_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolver_dobjective_0_n_out(void) { return 1;}

casadi_real FORCESNLPsolver_dobjective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver_dobjective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver_dobjective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_dobjective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_dobjective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

int FORCESNLPsolver_dobjective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver_dynamics_0:(i0[7],i1[2])->(o0[5]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][2] : 0;
  a1=1.6666666666666666e-02;
  a2=arg[0]? arg[0][4] : 0;
  a3=arg[0]? arg[0][5] : 0;
  a4=5.0000000000000000e-01;
  a5=arg[0]? arg[0][6] : 0;
  a6=tan(a5);
  a6=(a4*a6);
  a6=atan(a6);
  a7=(a3+a6);
  a7=cos(a7);
  a7=(a2*a7);
  a8=2.;
  a9=5.0000000000000003e-02;
  a10=arg[0]? arg[0][0] : 0;
  a11=(a9*a10);
  a11=(a2+a11);
  a12=(a2/a4);
  a13=sin(a6);
  a12=(a12*a13);
  a13=(a9*a12);
  a13=(a3+a13);
  a14=arg[0]? arg[0][1] : 0;
  a15=(a9*a14);
  a15=(a5+a15);
  a15=tan(a15);
  a15=(a4*a15);
  a15=atan(a15);
  a16=(a13+a15);
  a16=cos(a16);
  a16=(a11*a16);
  a16=(a8*a16);
  a7=(a7+a16);
  a16=(a9*a10);
  a16=(a2+a16);
  a17=(a11/a4);
  a18=sin(a15);
  a17=(a17*a18);
  a18=(a9*a17);
  a18=(a3+a18);
  a9=(a9*a14);
  a9=(a5+a9);
  a9=tan(a9);
  a9=(a4*a9);
  a9=atan(a9);
  a19=(a18+a9);
  a19=cos(a19);
  a19=(a16*a19);
  a19=(a8*a19);
  a7=(a7+a19);
  a19=1.0000000000000001e-01;
  a20=(a19*a10);
  a20=(a2+a20);
  a21=(a16/a4);
  a22=sin(a9);
  a21=(a21*a22);
  a22=(a19*a21);
  a22=(a3+a22);
  a19=(a19*a14);
  a19=(a5+a19);
  a19=tan(a19);
  a19=(a4*a19);
  a19=atan(a19);
  a23=(a22+a19);
  a23=cos(a23);
  a23=(a20*a23);
  a7=(a7+a23);
  a7=(a1*a7);
  a0=(a0+a7);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a6=(a3+a6);
  a6=sin(a6);
  a6=(a2*a6);
  a13=(a13+a15);
  a13=sin(a13);
  a11=(a11*a13);
  a11=(a8*a11);
  a6=(a6+a11);
  a18=(a18+a9);
  a18=sin(a18);
  a16=(a16*a18);
  a16=(a8*a16);
  a6=(a6+a16);
  a22=(a22+a19);
  a22=sin(a22);
  a22=(a20*a22);
  a6=(a6+a22);
  a6=(a1*a6);
  a0=(a0+a6);
  if (res[0]!=0) res[0][1]=a0;
  a0=(a8*a10);
  a0=(a10+a0);
  a6=(a8*a10);
  a0=(a0+a6);
  a0=(a0+a10);
  a0=(a1*a0);
  a2=(a2+a0);
  if (res[0]!=0) res[0][2]=a2;
  a17=(a8*a17);
  a12=(a12+a17);
  a21=(a8*a21);
  a12=(a12+a21);
  a20=(a20/a4);
  a19=sin(a19);
  a20=(a20*a19);
  a12=(a12+a20);
  a12=(a1*a12);
  a3=(a3+a12);
  if (res[0]!=0) res[0][3]=a3;
  a3=(a8*a14);
  a3=(a14+a3);
  a8=(a8*a14);
  a3=(a3+a8);
  a3=(a3+a14);
  a1=(a1*a3);
  a5=(a5+a1);
  if (res[0]!=0) res[0][4]=a5;
  return 0;
}

int FORCESNLPsolver_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int FORCESNLPsolver_dynamics_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver_dynamics_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver_dynamics_0_free_mem(int mem) {
}

int FORCESNLPsolver_dynamics_0_checkout(void) {
  return 0;
}

void FORCESNLPsolver_dynamics_0_release(int mem) {
}

void FORCESNLPsolver_dynamics_0_incref(void) {
}

void FORCESNLPsolver_dynamics_0_decref(void) {
}

casadi_int FORCESNLPsolver_dynamics_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolver_dynamics_0_n_out(void) { return 1;}

casadi_real FORCESNLPsolver_dynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver_dynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver_dynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_dynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_dynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

int FORCESNLPsolver_dynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver_ddynamics_0:(i0[7],i1[2])->(o0[5x7,21nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a6, a7, a8, a9;
  a0=1.6666666666666666e-02;
  a1=2.;
  a2=5.0000000000000003e-02;
  a3=arg[0]? arg[0][5] : 0;
  a4=arg[0]? arg[0][4] : 0;
  a5=5.0000000000000000e-01;
  a6=(a4/a5);
  a7=arg[0]? arg[0][6] : 0;
  a8=tan(a7);
  a8=(a5*a8);
  a9=atan(a8);
  a10=sin(a9);
  a11=(a6*a10);
  a11=(a2*a11);
  a11=(a3+a11);
  a12=arg[0]? arg[0][1] : 0;
  a13=(a2*a12);
  a13=(a7+a13);
  a14=tan(a13);
  a14=(a5*a14);
  a15=atan(a14);
  a16=(a11+a15);
  a17=cos(a16);
  a18=(a2*a17);
  a18=(a1*a18);
  a19=arg[0]? arg[0][0] : 0;
  a20=(a2*a19);
  a20=(a4+a20);
  a21=(a20/a5);
  a22=sin(a15);
  a23=(a21*a22);
  a23=(a2*a23);
  a23=(a3+a23);
  a24=(a2*a12);
  a24=(a7+a24);
  a25=tan(a24);
  a25=(a5*a25);
  a26=atan(a25);
  a27=(a23+a26);
  a28=cos(a27);
  a29=(a2*a28);
  a30=(a2*a19);
  a30=(a4+a30);
  a27=sin(a27);
  a31=1.0000000000000001e-01;
  a32=(a31*a22);
  a33=(a2*a32);
  a34=(a27*a33);
  a34=(a30*a34);
  a29=(a29-a34);
  a29=(a1*a29);
  a18=(a18+a29);
  a29=(a30/a5);
  a34=sin(a26);
  a35=(a29*a34);
  a35=(a31*a35);
  a35=(a3+a35);
  a12=(a31*a12);
  a12=(a7+a12);
  a36=tan(a12);
  a36=(a5*a36);
  a37=atan(a36);
  a38=(a35+a37);
  a39=cos(a38);
  a40=(a31*a39);
  a19=(a31*a19);
  a19=(a4+a19);
  a38=sin(a38);
  a41=(a31*a34);
  a42=(a31*a41);
  a43=(a38*a42);
  a43=(a19*a43);
  a40=(a40-a43);
  a18=(a18+a40);
  a18=(a0*a18);
  if (res[0]!=0) res[0][0]=a18;
  a11=(a11+a15);
  a18=sin(a11);
  a40=(a2*a18);
  a40=(a1*a40);
  a23=(a23+a26);
  a43=sin(a23);
  a44=(a2*a43);
  a23=cos(a23);
  a33=(a23*a33);
  a33=(a30*a33);
  a44=(a44+a33);
  a44=(a1*a44);
  a40=(a40+a44);
  a35=(a35+a37);
  a44=sin(a35);
  a33=(a31*a44);
  a35=cos(a35);
  a42=(a35*a42);
  a42=(a19*a42);
  a33=(a33+a42);
  a40=(a40+a33);
  a40=(a0*a40);
  if (res[0]!=0) res[0][1]=a40;
  if (res[0]!=0) res[0][2]=a31;
  a32=(a1*a32);
  a41=(a1*a41);
  a32=(a32+a41);
  a41=2.0000000000000001e-01;
  a40=sin(a37);
  a41=(a41*a40);
  a32=(a32+a41);
  a32=(a0*a32);
  if (res[0]!=0) res[0][3]=a32;
  a16=sin(a16);
  a13=cos(a13);
  a13=casadi_sq(a13);
  a32=(a2/a13);
  a32=(a5*a32);
  a41=1.;
  a14=casadi_sq(a14);
  a14=(a41+a14);
  a32=(a32/a14);
  a33=(a16*a32);
  a33=(a20*a33);
  a33=(a1*a33);
  a15=cos(a15);
  a42=(a15*a32);
  a42=(a21*a42);
  a45=(a2*a42);
  a24=cos(a24);
  a24=casadi_sq(a24);
  a46=(a2/a24);
  a46=(a5*a46);
  a25=casadi_sq(a25);
  a25=(a41+a25);
  a46=(a46/a25);
  a47=(a45+a46);
  a47=(a27*a47);
  a47=(a30*a47);
  a47=(a1*a47);
  a33=(a33+a47);
  a26=cos(a26);
  a47=(a26*a46);
  a47=(a29*a47);
  a48=(a31*a47);
  a12=cos(a12);
  a12=casadi_sq(a12);
  a49=(a31/a12);
  a49=(a5*a49);
  a36=casadi_sq(a36);
  a36=(a41+a36);
  a49=(a49/a36);
  a50=(a48+a49);
  a50=(a38*a50);
  a50=(a19*a50);
  a33=(a33+a50);
  a33=(a0*a33);
  a33=(-a33);
  if (res[0]!=0) res[0][4]=a33;
  a11=cos(a11);
  a32=(a11*a32);
  a32=(a20*a32);
  a32=(a1*a32);
  a45=(a45+a46);
  a45=(a23*a45);
  a45=(a30*a45);
  a45=(a1*a45);
  a32=(a32+a45);
  a48=(a48+a49);
  a48=(a35*a48);
  a48=(a19*a48);
  a32=(a32+a48);
  a32=(a0*a32);
  if (res[0]!=0) res[0][5]=a32;
  a42=(a1*a42);
  a47=(a1*a47);
  a42=(a42+a47);
  a47=(a19/a5);
  a37=cos(a37);
  a49=(a37*a49);
  a49=(a47*a49);
  a42=(a42+a49);
  a42=(a0*a42);
  if (res[0]!=0) res[0][6]=a42;
  if (res[0]!=0) res[0][7]=a31;
  if (res[0]!=0) res[0][8]=a41;
  if (res[0]!=0) res[0][9]=a41;
  a42=(a3+a9);
  a49=cos(a42);
  a10=(a1*a10);
  a32=(a2*a10);
  a48=(a16*a32);
  a48=(a20*a48);
  a17=(a17-a48);
  a17=(a1*a17);
  a49=(a49+a17);
  a22=(a1*a22);
  a17=(a2*a22);
  a48=(a27*a17);
  a48=(a30*a48);
  a28=(a28-a48);
  a28=(a1*a28);
  a49=(a49+a28);
  a34=(a1*a34);
  a28=(a31*a34);
  a48=(a38*a28);
  a48=(a19*a48);
  a39=(a39-a48);
  a49=(a49+a39);
  a49=(a0*a49);
  if (res[0]!=0) res[0][10]=a49;
  a3=(a3+a9);
  a49=sin(a3);
  a32=(a11*a32);
  a32=(a20*a32);
  a18=(a18+a32);
  a18=(a1*a18);
  a49=(a49+a18);
  a17=(a23*a17);
  a17=(a30*a17);
  a43=(a43+a17);
  a43=(a1*a43);
  a49=(a49+a43);
  a28=(a35*a28);
  a28=(a19*a28);
  a44=(a44+a28);
  a49=(a49+a44);
  a49=(a0*a49);
  if (res[0]!=0) res[0][11]=a49;
  if (res[0]!=0) res[0][12]=a41;
  a22=(a1*a22);
  a10=(a10+a22);
  a34=(a1*a34);
  a10=(a10+a34);
  a40=(a1*a40);
  a10=(a10+a40);
  a10=(a0*a10);
  if (res[0]!=0) res[0][13]=a10;
  a42=sin(a42);
  a10=(a4*a42);
  a40=(a20*a16);
  a40=(a1*a40);
  a10=(a10+a40);
  a40=(a30*a27);
  a40=(a1*a40);
  a10=(a10+a40);
  a40=(a19*a38);
  a10=(a10+a40);
  a10=(a0*a10);
  a10=(-a10);
  if (res[0]!=0) res[0][14]=a10;
  a3=cos(a3);
  a10=(a4*a3);
  a40=(a20*a11);
  a40=(a1*a40);
  a10=(a10+a40);
  a40=(a30*a23);
  a40=(a1*a40);
  a10=(a10+a40);
  a40=(a19*a35);
  a10=(a10+a40);
  a10=(a0*a10);
  if (res[0]!=0) res[0][15]=a10;
  if (res[0]!=0) res[0][16]=a41;
  a7=cos(a7);
  a7=casadi_sq(a7);
  a7=(a5/a7);
  a8=casadi_sq(a8);
  a8=(a41+a8);
  a7=(a7/a8);
  a42=(a42*a7);
  a42=(a4*a42);
  a9=cos(a9);
  a9=(a9*a7);
  a6=(a6*a9);
  a9=(a2*a6);
  a13=(a5/a13);
  a13=(a13/a14);
  a14=(a9+a13);
  a16=(a16*a14);
  a16=(a20*a16);
  a16=(a1*a16);
  a42=(a42+a16);
  a15=(a15*a13);
  a21=(a21*a15);
  a2=(a2*a21);
  a24=(a5/a24);
  a24=(a24/a25);
  a25=(a2+a24);
  a27=(a27*a25);
  a27=(a30*a27);
  a27=(a1*a27);
  a42=(a42+a27);
  a26=(a26*a24);
  a29=(a29*a26);
  a31=(a31*a29);
  a5=(a5/a12);
  a5=(a5/a36);
  a36=(a31+a5);
  a38=(a38*a36);
  a38=(a19*a38);
  a42=(a42+a38);
  a42=(a0*a42);
  a42=(-a42);
  if (res[0]!=0) res[0][17]=a42;
  a3=(a3*a7);
  a4=(a4*a3);
  a9=(a9+a13);
  a11=(a11*a9);
  a20=(a20*a11);
  a20=(a1*a20);
  a4=(a4+a20);
  a2=(a2+a24);
  a23=(a23*a2);
  a30=(a30*a23);
  a30=(a1*a30);
  a4=(a4+a30);
  a31=(a31+a5);
  a35=(a35*a31);
  a19=(a19*a35);
  a4=(a4+a19);
  a4=(a0*a4);
  if (res[0]!=0) res[0][18]=a4;
  a21=(a1*a21);
  a6=(a6+a21);
  a1=(a1*a29);
  a6=(a6+a1);
  a37=(a37*a5);
  a47=(a47*a37);
  a6=(a6+a47);
  a0=(a0*a6);
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a41;
  return 0;
}

int FORCESNLPsolver_ddynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int FORCESNLPsolver_ddynamics_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver_ddynamics_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver_ddynamics_0_free_mem(int mem) {
}

int FORCESNLPsolver_ddynamics_0_checkout(void) {
  return 0;
}

void FORCESNLPsolver_ddynamics_0_release(int mem) {
}

void FORCESNLPsolver_ddynamics_0_incref(void) {
}

void FORCESNLPsolver_ddynamics_0_decref(void) {
}

casadi_int FORCESNLPsolver_ddynamics_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolver_ddynamics_0_n_out(void) { return 1;}

casadi_real FORCESNLPsolver_ddynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver_ddynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver_ddynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_ddynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_ddynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

int FORCESNLPsolver_ddynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver_objective_1:(i0[7],i1[2])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=200.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a1=casadi_sq(a1);
  a1=(a0*a1);
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[1]? arg[1][1] : 0;
  a2=(a2-a3);
  a2=casadi_sq(a2);
  a0=(a0*a2);
  a1=(a1+a0);
  a0=2.0000000000000001e-01;
  a2=arg[0]? arg[0][0] : 0;
  a2=casadi_sq(a2);
  a2=(a0*a2);
  a1=(a1+a2);
  a2=arg[0]? arg[0][1] : 0;
  a2=casadi_sq(a2);
  a0=(a0*a2);
  a1=(a1+a0);
  if (res[0]!=0) res[0][0]=a1;
  return 0;
}

int FORCESNLPsolver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int FORCESNLPsolver_objective_1_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver_objective_1_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver_objective_1_free_mem(int mem) {
}

int FORCESNLPsolver_objective_1_checkout(void) {
  return 0;
}

void FORCESNLPsolver_objective_1_release(int mem) {
}

void FORCESNLPsolver_objective_1_incref(void) {
}

void FORCESNLPsolver_objective_1_decref(void) {
}

casadi_int FORCESNLPsolver_objective_1_n_in(void) { return 2;}

casadi_int FORCESNLPsolver_objective_1_n_out(void) { return 1;}

casadi_real FORCESNLPsolver_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int FORCESNLPsolver_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver_dobjective_1:(i0[7],i1[2])->(o0[1x7,4nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=2.0000000000000001e-01;
  a1=arg[0]? arg[0][0] : 0;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0]? arg[0][1] : 0;
  a1=(a1+a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=200.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[0]? arg[0][3] : 0;
  a2=arg[1]? arg[1][1] : 0;
  a1=(a1-a2);
  a1=(a1+a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][3]=a0;
  return 0;
}

int FORCESNLPsolver_dobjective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

int FORCESNLPsolver_dobjective_1_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver_dobjective_1_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver_dobjective_1_free_mem(int mem) {
}

int FORCESNLPsolver_dobjective_1_checkout(void) {
  return 0;
}

void FORCESNLPsolver_dobjective_1_release(int mem) {
}

void FORCESNLPsolver_dobjective_1_incref(void) {
}

void FORCESNLPsolver_dobjective_1_decref(void) {
}

casadi_int FORCESNLPsolver_dobjective_1_n_in(void) { return 2;}

casadi_int FORCESNLPsolver_dobjective_1_n_out(void) { return 1;}

casadi_real FORCESNLPsolver_dobjective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver_dobjective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver_dobjective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_dobjective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_dobjective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

int FORCESNLPsolver_dobjective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
